 ------------------------------------------------------------------------------
 -- Copyright 1994 International Computer Science Institute                  --
 -- Copyright 2007 Michael R. Taylor                                         --
 --                                                                          --
 -- This file is part of GNU Sather (compiler)                               --
 --                                                                          --
 -- GNU Sather (compiler) is free software; you can redistribute it and/or   --
 -- modify it under the terms of the GNU General Public License as           --
 -- published by the Free Software Foundation; either version 3 of the       --
 -- License, or (at your option) any later version.                          --
 --                                                                          --
 -- GNU Sather (compiler) is distributed in the hope that it will be useful, --
 -- but WITHOUT ANY WARRANTY; without even the implied warranty of           --
 -- MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU         --
 -- General Public License for more details.                                 --
 --                                                                          --
 -- You should have received a copy of the GNU General Public License        --
 -- along with this program. If not, see <http://www.gnu.org/licenses/>.     --
 ------------------------------------------------------------------------------

(*

COMPILER STAGES

These are code and any associated state that manipulates the vari ous
internal representations in the compiler.  They are abstracted so that
modules with differing functionality can be plugged in (for example, a
different back-end).  They are: $GET_OPTIONS, $PARSE, $FIND_TYPES,
$BUILD_TYPE_GRAPH, $CHECK_IFC_CONFORMANCE, $GET_MAIN, $GENERATE_AM,
$INLINE, $OPTIMIZE, $BACK_END, and $CHECK_AM.  Each of these has a
particular implementation in the compiler; for instance, CGEN is the C
generating $BACK_END.  CGEN and GET_OPTIONS have their own
subdirectories.

*)

abstract_syntax/Abstract_Syntax.module
front/Front.module
middle/Middle.module
back/Back.module
abstract_machine/Abstract_Machine.module
configuration/Configuration.module
representation/Representation.module

-verbose
sacomp.sa

-main CS
