 ------------------------------------------------------------------------------
 -- Copyright 1994 International Computer Science Institute                  --
 -- Copyright 2007 Michael R. Taylor                                         --
 --                                                                          --
 -- This file is part of GNU Sather (compiler)                               --
 --                                                                          --
 -- GNU Sather (compiler) is free software; you can redistribute it and/or   --
 -- modify it under the terms of the GNU General Public License as           --
 -- published by the Free Software Foundation; either version 3 of the       --
 -- License, or (at your option) any later version.                          --
 --                                                                          --
 -- GNU Sather (compiler) is distributed in the hope that it will be useful, --
 -- but WITHOUT ANY WARRANTY; without even the implied warranty of           --
 -- MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU         --
 -- General Public License for more details.                                 --
 --                                                                          --
 -- You should have received a copy of the GNU General Public License        --
 -- along with this program. If not, see <http://www.gnu.org/licenses/>.     --
 ------------------------------------------------------------------------------

(*

CONFIGURATION

GET_OPTIONS: This is the standard options module for the Sather
compiler. It is meant to be included in classes which specialize for a
particular configuration, and handles all the options needed by any
tool built using the compiler components - the location of the library
home, getting file names, interpreting command files.  A browser, for
example, might include this and then define additional options
appropriate to browsing.

CODE_OPTIONS: This adds options needed for anything that generates
code; it han dles optional checking flags such as "-pre" and
"-no_pre".

CS_OPTIONS: This adds options specific to the compiler.  It also reads
in the file "System/CONFIG".

*)

cs_options.sa
get_options.sa
system_lex.sa
config.sa
